global:
    scrape_interval: 10s 
    evaluation_interval: 10s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['192.168.0.10:9090']

    - job_name: 'api-sensors'
      static_configs:
      - targets: ['192.168.0.10:4000']
      metrics_path: /metrics-text