{
 "title": "API Sensors",
 "description": "Dashboard to view requests of API Sensors",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Events Created",
   "type": "stat",
   "description": "Events received and saved",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "events_sensors_api_call_to_create_event"
    }
   ]
  },
  {
   "title": "Request per Minute",
   "type": "graph",
   "description": "Transations of request per minute",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(application_httprequests_transactions_count[1m])"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Calls of Last Events Created",
   "type": "graph",
   "description": "Number of Call to get Last events created",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "events_sensors_api_call_last_events_created"
    }
   ]
  },
  {
   "title": "Calls per Region",
   "type": "graph",
   "description": "Number of Calls to get events per region",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "events_sensors_api_call_region_events_created"
    }
   ]
  },
  {
   "title": "Calls Total Values of Events",
   "type": "graph",
   "description": "Calls to get total values of events",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "events_sensors_api_call_valeus_events_created"
    }
   ]
  }
 ]
}